class SecurityReporter:
    """
    The third head of the Hydra.
    Consolidates findings from the StateStore into professional Markdown and Plaintext reports.
    """
    
    def __init__(self, store):
        self.store = store
        
    def generate_markdown_report(self) -> str:
        """Retrieves findings and builds a formatted Markdown document."""
        findings = self.store._get_all_findings()
        
        if not findings:
            return "# Hydra Security Report\n\nNo high-confidence vulnerabilities found."
            
        report = ["# Hydra Security Report", "\n## Summary", f"Total vulnerabilities identified: **{len(findings)}**"]
        
        report.append("\n| Severity | Type | URL | Confidence |")
        report.append("| :--- | :--- | :--- | :--- |")
        for f in findings:
            report.append(f"| {f['severity']} | {f['type']} | {f['url']} | {f['confidence']} |")
            
        report.append("\n## Detailed Findings")
        for f in findings:
            report.append(f"\n### {f['type']} ({f['severity']})")
            report.append(f"- **URL**: {f['url']}\n- **Description**: {f['description']}\n- **Evidence**: `{f['evidence']}`\n- **Confidence Score**: {f['confidence']}\n- **Detected At**: {f['timestamp']}")
            if f.get("poc"):
                report.append(f"\n#### Proof of Concept\n```python\n{f['poc']}\n```")
            report.append("\n---")
            
        report.append("\n\n*Report generated by Hydra Security Agent.*")
        return "\n".join(report)

    def generate_text_report(self) -> str:
        """Retrieves findings and builds a professional Plaintext document with ASCII separators."""
        findings = self.store._get_all_findings()
        
        if not findings:
            return "HYDRA SECURITY REPORT\n" + "="*21 + "\n\nNo high-confidence vulnerabilities found."

        sep_thick = "=" * 60
        sep_thin = "-" * 60
        
        report = [
            sep_thick,
            " HYDRA SECURITY REPORT ".center(60, " "),
            sep_thick,
            f"\n[SUMMARY]",
            f"Target: {findings[0]['url'] if findings else 'N/A'}",
            f"Total Vulnerabilities: {len(findings)}",
            f"Generated At: {findings[0]['timestamp'] if findings else 'N/A'}",
            f"\n{sep_thin}",
            f"| {'SEV':<8} | {'TYPE':<30} | {'CONF':<8} |",
            f"{sep_thin}"
        ]
        
        for f in findings:
            report.append(f"| {f['severity']:<8} | {f['type'][:30]:<30} | {f['confidence']:<8} |")
        
        report.append(f"{sep_thin}\n\n[DETAILED FINDINGS]")
        
        for f in findings:
            report.append(f"\n[{f['severity']}] {f['type']}")
            report.append(f"URL: {f['url']}")
            report.append(f"Description: {f['description']}")
            report.append(f"Evidence: {f['evidence']}")
            report.append(f"Confidence: {f['confidence']}")
            
            if f.get("poc"):
                report.append("\n[PROOF OF CONCEPT]")
                report.append(f"{f['poc']}")
            
            report.append(f"\n{sep_thin}")

        report.append("\nReport generated by Hydra Security Agent.")
        return "\n".join(report)
