class SecurityReporter:
    """
    The third head of the Hydra.
    Consolidates findings from the StateStore into a professional Markdown report.
    """
    
    def __init__(self, store):
        self.store = store
        
    def generate_markdown_report(self) -> str:
        """
        Retrieves all findings and builds a formatted Markdown document.
        """
        findings = self.store._get_all_findings()
        
        if not findings:
            return "# Hydra Security Report\n\nNo high-confidence vulnerabilities found."
            
        report = []
        report.append("# Hydra Security Report")
        report.append("\n## Summary")
        report.append(f"Total vulnerabilities identified: **{len(findings)}**")
        
        # Simple table for quick overview
        report.append("\n| Severity | Type | URL | Confidence |")
        report.append("| :--- | :--- | :--- | :--- |")
        for f in findings:
            report.append(f"| {f['severity']} | {f['type']} | {f['url']} | {f['confidence']} |")
            
        report.append("\n## Detailed Findings")
        
        for f in findings:
            report.append(f"\n### {f['type']} ({f['severity']})")
            report.append(f"- **URL**: {f['url']}")
            report.append(f"- **Description**: {f['description']}")
            report.append(f"- **Evidence**: `{f['evidence']}`")
            report.append(f"- **Confidence Score**: {f['confidence']}")
            report.append(f"- **Detected At**: {f['timestamp']}")
            
            if f.get("poc"):
                report.append("\n#### Proof of Concept")
                report.append(f"```python\n{f['poc']}\n```")
                
            report.append("\n---")
            
        report.append("\n\n*Report generated by Hydra Security Agent.*")
        
        return "\n".join(report)
